package projections_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/miroslav-matejovsky/ordr/graph"
	"github.com/miroslav-matejovsky/ordr/knowledge"
	"github.com/miroslav-matejovsky/ordr/projections"
)

func fixture(t *testing.T) (knowledge.Register, graph.Graph) {
	t.Helper()
	ops := []knowledge.Opportunity{
		{ID: "gamma", Title: "Gamma", State: knowledge.StateFraming, Hypothesis: "H3", Decision: "D3",
			Uncertainties: []string{"U3"}},
		{ID: "alpha", Title: "Alpha", State: knowledge.StateOptions, Hypothesis: "H1", Decision: "D1",
			Evidence: []string{"E1"}},
		{ID: "beta", Title: "Beta", State: knowledge.StateOptions, Hypothesis: "H2", Decision: "D2"},
	}
	r, err := knowledge.NewRegister(ops)
	require.NoError(t, err)
	g, err := graph.New(r.IDs(),
		[]graph.Comparison{
			{Dimension: graph.Value, More: "beta", Less: "alpha", Origin: "o.cue:1:1"},
			{Dimension: graph.Complexity, More: "alpha", Less: "beta", Origin: "o.cue:2:1"},
			{Dimension: graph.Complexity, More: "alpha", Less: "gamma", Origin: "o.cue:3:1"},
		},
		[]graph.Relation{
			{Kind: graph.Blocks, From: "gamma", To: "alpha", Origin: "r.cue:1:1"},
			{Kind: graph.Relates, From: "gamma", To: "beta", Origin: "r.cue:2:1"},
		})
	require.NoError(t, err)
	return r, g
}

func TestRenderOrdering(t *testing.T) {
	r, g := fixture(t)
	tests := []struct {
		kind projections.Kind
		want string
	}{
		{projections.ValueOrdering, `# Strategic Value Ordering

<!-- Generated by ordr from knowledge and graph sources. Do not edit; regenerate with ` + "`ordr project`" + `. -->

Which opportunity is more strategically valuable?

Level 1 ranks highest. Items on the same level are not ordered against each other.

## Levels

1. beta (Beta)
2. alpha (Alpha)

## Not compared

- gamma (Gamma)

## Stated comparisons

- beta has more strategic value than alpha (` + "`o.cue:1:1`" + `)
`},
		{projections.ComplexityOrdering, `# Complexity Ordering

<!-- Generated by ordr from knowledge and graph sources. Do not edit; regenerate with ` + "`ordr project`" + `. -->

Which opportunity is more complex?

Level 1 ranks highest. Items on the same level are not ordered against each other.

## Levels

1. alpha (Alpha)
2. beta (Beta); gamma (Gamma)

## Not compared

None.

## Stated comparisons

- alpha is more complex than beta (` + "`o.cue:2:1`" + `)
- alpha is more complex than gamma (` + "`o.cue:3:1`" + `)
`},
		{projections.UncertaintyOrdering, `# Uncertainty Ordering

<!-- Generated by ordr from knowledge and graph sources. Do not edit; regenerate with ` + "`ordr project`" + `. -->

Which opportunity is more uncertain?

Level 1 ranks highest. Items on the same level are not ordered against each other.

## Levels

No comparisons stated.

## Not compared

- alpha (Alpha)
- beta (Beta)
- gamma (Gamma)

## Stated comparisons

None.
`},
	}
	for _, tt := range tests {
		t.Run(string(tt.kind), func(t *testing.T) {
			doc := projections.Render(tt.kind, r, g)
			require.Equal(t, string(tt.kind)+".md", doc.Name)
			require.Equal(t, tt.want, doc.Content)
		})
	}
}

func TestRenderReadiness(t *testing.T) {
	r, g := fixture(t)
	doc := projections.Render(projections.Readiness, r, g)
	require.Equal(t, `# Decision Readiness

<!-- Generated by ordr from knowledge and graph sources. Do not edit; regenerate with `+"`ordr project`"+`. -->

Workflow: framing -> investigation -> evidence -> options -> decision-ready

Grouped by state, most advanced first. Within a state, higher strategic value comes first.

## decision-ready

None.

## options

### beta: Beta

- Decision to prepare: D2
- Current hypothesis: H2
- Evidence: None recorded.
- Open uncertainties: None recorded.
- Related to: gamma (Gamma)

### alpha: Alpha

- Decision to prepare: D1
- Current hypothesis: H1
- Evidence:
  - E1
- Open uncertainties: None recorded.
- Blocked by: gamma (Gamma)

## evidence

None.

## investigation

None.

## framing

### gamma: Gamma

- Decision to prepare: D3
- Current hypothesis: H3
- Evidence: None recorded.
- Open uncertainties:
  - U3
- Related to: beta (Beta)
`, doc.Content)
}

func TestRenderIsDeterministic(t *testing.T) {
	r, g := fixture(t)
	for _, k := range projections.Kinds() {
		first := projections.Render(k, r, g)
		for range 20 {
			require.Equal(t, first, projections.Render(k, r, g))
		}
	}
}

func TestSelect(t *testing.T) {
	kinds, err := projections.Select("all")
	require.NoError(t, err)
	require.Equal(t, projections.Kinds(), kinds)

	kinds, err = projections.Select("relationships")
	require.NoError(t, err)
	require.Equal(t, []projections.Kind{projections.Relationships}, kinds)

	_, err = projections.Select("score")
	require.ErrorContains(t, err, `unknown projection "score"`)
}
