// Package projections renders views derived from knowledge and graph data.
//
// Projections are disposable: they are pure functions of a
// [knowledge.Register] and a [graph.Graph], produce deterministic Markdown and
// never modify their inputs. Reading sources and writing output belong to the
// workspace package.
package projections

import (
	"fmt"
	"slices"
	"strings"

	"github.com/miroslav-matejovsky/ordr/graph"
	"github.com/miroslav-matejovsky/ordr/knowledge"
)

// Kind names a projection.
type Kind string

// Available projections.
const (
	ValueOrdering       Kind = "value"
	UncertaintyOrdering Kind = "uncertainty"
	ComplexityOrdering  Kind = "complexity"
	Relationships       Kind = "relationships"
	Readiness           Kind = "readiness"
)

// All selects every projection in Select.
const All = "all"

// Kinds returns all projections in a fixed order.
func Kinds() []Kind {
	return []Kind{ValueOrdering, UncertaintyOrdering, ComplexityOrdering, Relationships, Readiness}
}

// Select resolves a projection name, or All, into kinds.
func Select(name string) ([]Kind, error) {
	if name == All {
		return Kinds(), nil
	}
	if slices.Contains(Kinds(), Kind(name)) {
		return []Kind{Kind(name)}, nil
	}
	return nil, fmt.Errorf("unknown projection %q: expected %s or one of %v", name, All, Kinds())
}

// Document is a rendered projection. Name is a plain file name.
type Document struct {
	Name    string
	Content string
}

// Render produces the projection k.
func Render(k Kind, r knowledge.Register, g graph.Graph) Document {
	var b strings.Builder
	switch k {
	case ValueOrdering:
		renderOrdering(&b, r, g, orderings[graph.Value])
	case UncertaintyOrdering:
		renderOrdering(&b, r, g, orderings[graph.Uncertainty])
	case ComplexityOrdering:
		renderOrdering(&b, r, g, orderings[graph.Complexity])
	case Relationships:
		renderRelationships(&b, r, g)
	case Readiness:
		renderReadiness(&b, r, g)
	default:
		panic(fmt.Sprintf("projections: unknown kind %q", k))
	}
	return Document{Name: string(k) + ".md", Content: strings.TrimRight(b.String(), "\n") + "\n"}
}

const generatedNote = "<!-- Generated by ordr from knowledge and graph sources. Do not edit; regenerate with `ordr project`. -->\n"

type orderingText struct {
	dim      graph.Dimension
	title    string
	question string
	more     string // phrase for "a <more> b"
}

var orderings = map[graph.Dimension]orderingText{
	graph.Value: {graph.Value, "Strategic Value Ordering",
		"Which opportunity is more strategically valuable?", "has more strategic value than"},
	graph.Uncertainty: {graph.Uncertainty, "Uncertainty Ordering",
		"Which opportunity is more uncertain?", "is more uncertain than"},
	graph.Complexity: {graph.Complexity, "Complexity Ordering",
		"Which opportunity is more complex?", "is more complex than"},
}

func renderOrdering(b *strings.Builder, r knowledge.Register, g graph.Graph, t orderingText) {
	ord := g.Order(t.dim)
	fmt.Fprintf(b, "# %s\n\n%s\n%s\n\n", t.title, generatedNote, t.question)
	b.WriteString("Level 1 ranks highest. Items on the same level are not ordered against each other.\n\n")

	b.WriteString("## Levels\n\n")
	if len(ord.Levels) == 0 {
		b.WriteString("No comparisons stated.\n\n")
	}
	for i, level := range ord.Levels {
		fmt.Fprintf(b, "%d. %s\n", i+1, joinLabels(r, level))
	}
	if len(ord.Levels) > 0 {
		b.WriteString("\n")
	}

	b.WriteString("## Not compared\n\n")
	writeList(b, labels(r, ord.Unranked), "None.")

	b.WriteString("## Stated comparisons\n\n")
	var stated []string
	for _, c := range g.Comparisons(t.dim) {
		stated = append(stated, fmt.Sprintf("%s %s %s (`%s`)", c.More, t.more, c.Less, c.Origin))
	}
	writeList(b, stated, "None.")
}

var relationPhrases = map[graph.RelationKind]string{
	graph.Supports:    "supports",
	graph.Blocks:      "blocks",
	graph.Enables:     "enables",
	graph.Invalidates: "invalidates",
	graph.Relates:     "relates to",
}

func renderRelationships(b *strings.Builder, r knowledge.Register, g graph.Graph) {
	fmt.Fprintf(b, "# Relationship Summary\n\n%s\n", generatedNote)
	rels := g.Relations()
	for _, k := range graph.RelationKinds() {
		fmt.Fprintf(b, "## %s\n\n", k)
		var lines []string
		for _, rel := range rels {
			if rel.Kind == k {
				lines = append(lines, fmt.Sprintf("%s %s %s (`%s`)",
					label(r, rel.From), relationPhrases[k], label(r, rel.To), rel.Origin))
			}
		}
		writeList(b, lines, "None.")
	}
}

// incoming lists, per relation kind, how a relation pointing at a record is
// described from that record's point of view.
var incoming = []struct {
	kind  graph.RelationKind
	label string
}{
	{graph.Blocks, "Blocked by"},
	{graph.Invalidates, "Invalidated by"},
	{graph.Enables, "Depends on"},
	{graph.Supports, "Supported by"},
}

func renderReadiness(b *strings.Builder, r knowledge.Register, g graph.Graph) {
	fmt.Fprintf(b, "# Decision Readiness\n\n%s\n", generatedNote)
	states := knowledge.States()
	var flow []string
	for _, s := range states {
		flow = append(flow, string(s))
	}
	fmt.Fprintf(b, "Workflow: %s\n\n", strings.Join(flow, " -> "))
	b.WriteString("Grouped by state, most advanced first. Within a state, higher strategic value comes first.\n\n")

	order := valueOrder(g, r)
	rels := g.Relations()
	for _, s := range slices.Backward(states) {
		fmt.Fprintf(b, "## %s\n\n", s)
		var inState []knowledge.Opportunity
		for _, id := range order {
			if o, _ := r.Opportunity(id); o.State == s {
				inState = append(inState, o)
			}
		}
		if len(inState) == 0 {
			b.WriteString("None.\n\n")
			continue
		}
		for _, o := range inState {
			renderReadinessEntry(b, r, rels, o)
		}
	}
}

func renderReadinessEntry(b *strings.Builder, r knowledge.Register, rels []graph.Relation, o knowledge.Opportunity) {
	fmt.Fprintf(b, "### %s: %s\n\n", o.ID, o.Title)
	fmt.Fprintf(b, "- Decision to prepare: %s\n", o.Decision)
	fmt.Fprintf(b, "- Current hypothesis: %s\n", o.Hypothesis)
	writeNested(b, "Evidence", o.Evidence, "None recorded.")
	writeNested(b, "Open uncertainties", o.Uncertainties, "None recorded.")
	for _, in := range incoming {
		var from []string
		for _, rel := range rels {
			if rel.Kind == in.kind && rel.To == o.ID {
				from = append(from, label(r, rel.From))
			}
		}
		if len(from) > 0 {
			fmt.Fprintf(b, "- %s: %s\n", in.label, strings.Join(from, "; "))
		}
	}
	var related []string
	for _, rel := range rels {
		if rel.Kind != graph.Relates {
			continue
		}
		switch o.ID {
		case rel.From:
			related = append(related, label(r, rel.To))
		case rel.To:
			related = append(related, label(r, rel.From))
		}
	}
	if len(related) > 0 {
		fmt.Fprintf(b, "- Related to: %s\n", strings.Join(related, "; "))
	}
	b.WriteString("\n")
}

// valueOrder flattens the value ordering: levels top down, then unranked ids.
func valueOrder(g graph.Graph, r knowledge.Register) []knowledge.ID {
	ord := g.Order(graph.Value)
	var ids []knowledge.ID
	for _, level := range ord.Levels {
		ids = append(ids, level...)
	}
	ids = append(ids, ord.Unranked...)
	if len(ids) != len(r.IDs()) {
		panic("projections: graph and register disagree on known ids")
	}
	return ids
}

func label(r knowledge.Register, id knowledge.ID) string {
	o, ok := r.Opportunity(id)
	if !ok {
		panic(fmt.Sprintf("projections: id %q not in register", id))
	}
	return fmt.Sprintf("%s (%s)", id, o.Title)
}

func labels(r knowledge.Register, ids []knowledge.ID) []string {
	out := make([]string, len(ids))
	for i, id := range ids {
		out[i] = label(r, id)
	}
	return out
}

func joinLabels(r knowledge.Register, ids []knowledge.ID) string {
	return strings.Join(labels(r, ids), "; ")
}

func writeList(b *strings.Builder, items []string, empty string) {
	if len(items) == 0 {
		fmt.Fprintf(b, "%s\n\n", empty)
		return
	}
	for _, item := range items {
		fmt.Fprintf(b, "- %s\n", item)
	}
	b.WriteString("\n")
}

func writeNested(b *strings.Builder, title string, items []string, empty string) {
	if len(items) == 0 {
		fmt.Fprintf(b, "- %s: %s\n", title, empty)
		return
	}
	fmt.Fprintf(b, "- %s:\n", title)
	for _, item := range items {
		fmt.Fprintf(b, "  - %s\n", item)
	}
}
